/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSyncJonbetRouteImport } from './routes/api.public.sync-jonbet'
import { Route as ApiPublicSaveStoneRouteImport } from './routes/api.public.save-stone'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncJonbetRoute = ApiPublicSyncJonbetRouteImport.update({
  id: '/api/public/sync-jonbet',
  path: '/api/public/sync-jonbet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSaveStoneRoute = ApiPublicSaveStoneRouteImport.update({
  id: '/api/public/save-stone',
  path: '/api/public/save-stone',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/save-stone': typeof ApiPublicSaveStoneRoute
  '/api/public/sync-jonbet': typeof ApiPublicSyncJonbetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/save-stone': typeof ApiPublicSaveStoneRoute
  '/api/public/sync-jonbet': typeof ApiPublicSyncJonbetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/save-stone': typeof ApiPublicSaveStoneRoute
  '/api/public/sync-jonbet': typeof ApiPublicSyncJonbetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/save-stone' | '/api/public/sync-jonbet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/save-stone' | '/api/public/sync-jonbet'
  id: '__root__' | '/' | '/api/public/save-stone' | '/api/public/sync-jonbet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicSaveStoneRoute: typeof ApiPublicSaveStoneRoute
  ApiPublicSyncJonbetRoute: typeof ApiPublicSyncJonbetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-jonbet': {
      id: '/api/public/sync-jonbet'
      path: '/api/public/sync-jonbet'
      fullPath: '/api/public/sync-jonbet'
      preLoaderRoute: typeof ApiPublicSyncJonbetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/save-stone': {
      id: '/api/public/save-stone'
      path: '/api/public/save-stone'
      fullPath: '/api/public/save-stone'
      preLoaderRoute: typeof ApiPublicSaveStoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicSaveStoneRoute: ApiPublicSaveStoneRoute,
  ApiPublicSyncJonbetRoute: ApiPublicSyncJonbetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
